### ISSUE TITLE
Syncronization problem

### ISSUE THREAD

**Issue by dav695** [aimotive/aimotive_dataset#5]
Hello, 
Congratulations on this fantastic work!
I am trying to use your dataset to test some fusion architectures. But I project the pointcloud lidar in the image, and sometimes I see a mismatch. Like this two examples in the motorbike (20210920-203858-00.22.38-00.22.53@Sogun): 
<img width="643" alt="sync2" src="https://github.com/aimotive/aimotive_dataset/assets/144144587/91bf21ab-7bf2-4f5d-9a98-152c93ad401d">
<img width="642" alt="pr1" src="https://github.com/aimotive/aimotive_dataset/assets/144144587/c305b5c6-fb6b-41cc-be16-854bded84a52">
Or this example in the highway (20220203-144759-00.40.00-00.40.15@Cali): 
<img width="548" alt="problem_front_img" src="https://github.com/aimotive/aimotive_dataset/assets/144144587/ec1703a8-a685-4b42-a6b9-bb91a92de023">

I think that the matrix transformations are correct. Do you know why this things happen? 
Thanks you so much!

**Comment by TamasMatuszka** [comment]
Hi @dav695, 

We updated our paper with the limitations that explain the mismatches:
"The sensor setup results in a synchronization limitation caused by the fact that sensors differ in the temporal recording method. Since the rotating LiDAR and rolling shutter cameras have different measurement methods, some discrepancies exist in temporally discretized annotations. This phenomenon is mostly visible when the relative speed difference between the ego and exo car is large." (https://arxiv.org/pdf/2211.09445.pdf)

However, the last case cannot be explained by this fact. We will investigate the problem. Thanks for letting us know! 

Since our baseline algorithms operate in BEV space, these synchronization issues did not cause significant problems for us. I hope the mismatches won't prevent you from utilizing the dataset.

**Comment by dav695** [comment]
Hello @TamasMatuszka , thanks you so much for the anmswer. I close the issue, and again congratulations!!
